// packages/client/src/components/GameConfig.tsx
import {
  AllRole,
  ExtPack,
  PackKey,
  PresetPoolPack,
  PvePresetActivePack,
  PvePresetActiveUnit,
  PvpPresetActivePack,
  PvpPresetActiveUnit,
  RoleData,
  RoleKey,
} from '@sctavern/data'
import { type GameConfig, LCG } from '@sctavern/emulator'
import { useNavigate } from 'react-router'

const lcg = new LCG(Math.floor(Math.random() * 100000))

const noPveRoles: RoleKey[] = [
  '雷诺',
  '阿塔尼斯',
  '科学球',
  '母舰核心',
  '行星要塞',
  '拟态虫',
  '探机',
  '泰凯斯',
  '诺娃',
  '思旺',
  '跳虫',
  '蒙斯克',
  '雷神',
  '机械哨兵',
  '异龙',
  '医疗兵',
  '分裂池',
  '响尾蛇',
  // '混合体',
  '德哈卡',
  '星港',
  '进化腔',
  '锻炉',
  '扎加拉',
  '大力神',
  '凯瑞甘',
  '米拉',
  '先知',
  '阿尔达瑞斯',
  '斯托科夫',
  '解放者',
  '干扰者',
]

function GameConfig() {
  const [config, setConfig] = useState<GameConfig>({
    Pack: ['核心'],
    Seed: Math.floor(Math.random() * 1000000),
    Role: ['白板'],
    Mutation: [],
    Pve: false,
    PoolPack: PresetPoolPack,
    ActivePack: PvpPresetActivePack,
    ActiveUnit: PvpPresetActiveUnit,
  })

  const navigate = useNavigate()

  const handlePackChange = useCallback(
    (event: React.ChangeEvent<HTMLInputElement>) => {
      setConfig(
        produce(config, draft => {
          if (event.target.checked) {
            draft.Pack.push(event.target.name as PackKey)
          } else {
            draft.Pack = draft.Pack.filter(p => p !== event.target.name)
          }
        })
      )
    },
    []
  )

  const allRole = AllRole.filter(r => !RoleData[r].ext)

  const handlePveChange = useCallback(
    (event: React.ChangeEvent<HTMLInputElement>) => {
      setConfig(
        produce(config, draft => {
          if (event.target.checked) {
            draft.Pve = true
            draft.ActivePack = PvePresetActivePack
            draft.ActiveUnit = PvePresetActiveUnit
          } else {
            draft.Pve = false
            draft.ActivePack = PvpPresetActivePack
            draft.ActiveUnit = PvpPresetActiveUnit
          }
        })
      )
    },
    []
  )

  return (
    <Container>
      <CardView>
        <CardContent className="InfoCard">
          <Box display="grid" gridTemplateColumns="repeat(12, 1fr)" rowGap={2}>
            <Box gridColumn="span 1"></Box>
            <Box gridColumn="span 8">
              <TextField
                fullWidth
                type="number"
                label="种子"
                value={config.Seed.toString()}
                onChange={event => {
                  setConfig(
                    produce(config, draft => {
                      draft.Seed = Math.floor(Number(event.target.value) ?? 1)
                    })
                  )
                }}
              ></TextField>
            </Box>
            <Box gridColumn="span 2" alignSelf="center" justifySelf="center">
              <Button
                variant="contained"
                onClick={() => {
                  setConfig(
                    produce(config, draft => {
                      draft.Seed = Math.floor(Math.random() * 1000000)
                    })
                  )
                }}
              >
                随机
              </Button>
            </Box>
            <Box gridColumn="span 1"></Box>
            <Box gridColumn="span 1"></Box>
            <Box
              gridColumn="span 8"
              display="grid"
              gridTemplateColumns="repeat(2, 1fr)"
            >
              {ExtPack.map((pack, index) => {
                return (
                  <FormControlLabel
                    key={index}
                    label={pack}
                    control={
                      <Checkbox
                        name={pack}
                        checked={config.Pack.includes(pack)}
                        onChange={handlePackChange}
                      ></Checkbox>
                    }
                  ></FormControlLabel>
                )
              })}
            </Box>{' '}
            <Box gridColumn="span 2" alignSelf="center" justifySelf="center">
              <Button
                variant="contained"
                onClick={() => {
                  setConfig(
                    produce(config, draft => {
                      draft.Pack = [
                        '核心',
                        ...lcg.shuffle(ExtPack.map(x => x)).slice(0, 2),
                      ]
                    })
                  )
                }}
              >
                随机
              </Button>
            </Box>
            <Box gridColumn="span 1"></Box>
            <Box gridColumn="span 1"></Box>
            <Box gridColumn="span 8">
              <FormControl fullWidth>
                <InputLabel>角色</InputLabel>
                <Select
                  label="角色"
                  value={config.Role[0]}
                  onChange={event => {
                    setConfig(
                      produce(config, draft => {
                        draft.Role = [event.target.value as RoleKey]
                      })
                    )
                  }}
                >
                  {allRole.map((role, index) => {
                    return (
                      <MenuItem value={role} key={index}>
                        {role}
                      </MenuItem>
                    )
                  })}
                </Select>
              </FormControl>
            </Box>{' '}
            <Box gridColumn="span 2" alignSelf="center" justifySelf="center">
              <Button
                variant="contained"
                onClick={() => {
                  setConfig(
                    produce(config, draft => {
                      draft.Role = [lcg.one_of(allRole) as RoleKey]
                    })
                  )
                }}
              >
                随机
              </Button>
            </Box>
            <Box gridColumn="span 1"></Box>
            <Box gridColumn="span 1"></Box>
            <Box gridColumn="span 2">
              <FormControlLabel
                label="启用PVE"
                control={
                  <Checkbox
                    name="启用PVE"
                    checked={config.Pve}
                    onChange={handlePveChange}
                  ></Checkbox>
                }
              ></FormControlLabel>
            </Box>
            <Box gridColumn="span 4" alignSelf="center">
              {config.Pve && noPveRoles.includes(config.Role[0])
                ? '警告: 当前角色的预言尚未完成'
                : ''}
            </Box>
          </Box>
        </CardContent>
        <CardActions>
          <Button
            onClick={() => {
              navigate(
                '/local/play?' +
                  new URLSearchParams({
                    config: JSON.stringify(config),
                  })
              )
            }}
          >
            开始
          </Button>
        </CardActions>
      </CardView>
    </Container>
  )
}

export default GameConfig

// packages/client/src/components/GameConfig.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import {
  type PackKey,
  type RoleKey,
  type MutationKey,
  ExtPack,
} from '@sctavern/data'
import { LCG } from '@sctavern/emulator'
import { useBrowserStore } from '@/stores/browser'

const browserStore = useBrowserStore()

const section = ref<'packseed' | 'role' | 'mutation' | 'pve'>('packseed')

const props = defineProps<{
  Pack: PackKey[]
  Seed: number
  Role: RoleKey[]
  Mutation: MutationKey[]

  Pve: boolean
}>()

const emit = defineEmits<{
  (e: 'update:Pack', p: PackKey[]): void
  (e: 'update:Seed', s: number): void
  (e: 'update:Role', r: RoleKey[]): void
  (e: 'update:Pve', p: boolean): void
  (e: 'ok'): void
}>()

const seed = computed({
  get() {
    return props.Seed
  },

  set(seed: number) {
    emit('update:Seed', seed)
  },
})

const pack = computed({
  get() {
    return props.Pack
  },

  set(pack: PackKey[]) {
    emit('update:Pack', pack)
  },
})

const role = computed({
  get() {
    return props.Role
  },

  set(role: RoleKey[]) {
    emit('update:Role', role)
  },
})

const pve = computed({
  get() {
    return props.Pve
  },

  set(pve: boolean) {
    emit('update:Pve', pve)
  },
})

const lcg = new LCG(genSeed())

function genSeed() {
  return Math.round(Math.random() * 100000000)
}

function genPack(): PackKey[] {
  return ['核心', ...lcg.shuffle(ExtPack.slice(1)).slice(0, 2)]
}

const AllRoleChoice = computed<RoleKey[]>(() => {
  return [
    '白板',
    '执政官',
    '狂热者',
    '陆战队员',
    '收割者',
    '幽灵',
    '感染虫',
    'SCV',
    '阿巴瑟',
    '工蜂',
    '王虫',
    '蟑螂',
    '副官',
    '追猎者',
    '使徒',
    '矿骡',
    '斯台特曼',
    '雷诺',
    '阿塔尼斯',
    '科学球',
    '母舰核心',
    '行星要塞',
    '拟态虫',
    '探机',
    '泰凯斯',
    '诺娃',
    '思旺',
    '跳虫',
    '蒙斯克',
    '雷神',
    '机械哨兵',
    '异龙',
    '医疗兵',
    '分裂池',
    '响尾蛇',
    '混合体',
    '德哈卡',
    '星港',
    '进化腔',
    '锻炉',
    '扎加拉',
    '大力神',
    '凯瑞甘',
    '米拉',
    '先知',
    '阿尔达瑞斯',
    '斯托科夫',
    '解放者',
  ]
})

const noPveRoles: RoleKey[] = [
  '追猎者',
  '使徒',
  '矿骡',
  '斯台特曼',
  '雷诺',
  '阿塔尼斯',
  '科学球',
  '母舰核心',
  '行星要塞',
  '拟态虫',
  '探机',
  '泰凯斯',
  '诺娃',
  '思旺',
  '跳虫',
  '蒙斯克',
  '雷神',
  '机械哨兵',
  '异龙',
  '医疗兵',
  '分裂池',
  '响尾蛇',
  // '混合体',
  '德哈卡',
  '星港',
  '进化腔',
  '锻炉',
  '扎加拉',
  '大力神',
  '凯瑞甘',
  '米拉',
  '先知',
  '阿尔达瑞斯',
  '斯托科夫',
  '解放者',
]

function genRole(): RoleKey[] {
  return lcg.shuffle(AllRoleChoice.value).slice(0, role.value.length)
}
</script>

<template>
  <v-card>
    <template v-if="!browserStore.isMobile || section === 'packseed'">
      <div class="d-flex">
        <v-col cols="1"></v-col>
        <v-col cols="8">
          <v-text-field
            v-model="seed"
            density="compact"
            hide-details
          ></v-text-field>
        </v-col>
        <v-col cols="2">
          <v-btn @click="seed = genSeed()"> 随机 </v-btn>
        </v-col>
      </div>
      <div class="d-flex">
        <v-col cols="1"></v-col>
        <v-col cols="4" class="d-flex flex-column">
          <v-checkbox
            v-model="pack"
            v-for="p in ExtPack.slice(0, 4)"
            :key="`Pack-${p}`"
            :label="p"
            :value="p"
            density="compact"
            hide-details
          ></v-checkbox> </v-col
        ><v-col cols="4" class="d-flex flex-column">
          <v-checkbox
            v-model="pack"
            v-for="p in ExtPack.slice(4)"
            :key="`Pack-${p}`"
            :label="p"
            :value="p"
            density="compact"
            hide-details
          ></v-checkbox>
        </v-col>
        <v-col cols="2">
          <v-btn @click="pack = genPack()"> 随机 </v-btn>
        </v-col>
      </div>
    </template>
    <template v-if="!browserStore.isMobile || section === 'role'">
      <div class="d-flex">
        <template v-if="role.length === 1">
          <v-col cols="1"></v-col>
          <v-col cols="8">
            <v-select
              hide-details
              density="compact"
              v-model="role[0]"
              :items="AllRoleChoice"
            ></v-select>
          </v-col>
          <v-col cols="2">
            <v-btn @click="role = genRole()"> 随机 </v-btn>
          </v-col>
        </template>
      </div>
    </template>
    <template v-if="!browserStore.isMobile || section === 'mutation'">
      <div class="d-flex">
        <v-col cols="1"></v-col>
        <v-col cols="8"> 暂时不支持选突变因子 </v-col>
      </div>
    </template>
    <template v-if="!browserStore.isMobile || section === 'pve'">
      <div class="d-flex">
        <v-col cols="1"></v-col>
        <v-col cols="8">
          <v-checkbox
            v-model="pve"
            density="compact"
            label="启用PVE内容"
            :error-messages="
              pve && noPveRoles.includes(role[0])
                ? ['警告: 当前角色的预言尚未完成']
                : []
            "
          ></v-checkbox>
        </v-col>
      </div>
    </template>
    <div style="min-width: 500px"></div>
    <v-card-actions>
      <template v-if="browserStore.isMobile">
        <v-btn @click="section = 'packseed'"> 种子卡包 </v-btn>
        <v-btn @click="section = 'role'"> 角色 </v-btn>
        <v-btn @click="section = 'mutation'"> 突变因子 </v-btn>
        <v-btn @click="section = 'pve'"> PVE </v-btn>
      </template>
      <v-btn class="ml-auto" color="primary" @click="$emit('ok')"> 启动 </v-btn>
    </v-card-actions>
  </v-card>
</template>
